namespace: venkatesh-ns

secret: 
  type: Opaque
  EMAIL_USER: Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=
  EMAIL_PASS: eXhvcSBianVrIHJkbnQgYWx6cA==

config:
  MONGODB_URI: "mongodb://mongodb:27017/myDatabase"
  SESSION_SECRET: "1234"
  PORT: "3130"
  MONGO_INITDB_DATABASE: "myDatabase"

deployment: 
  labels:
    app: retail
  name: retail-container
  replicas: 4

image:
  repository: saiteja2502/userprofile
  tag: retail:latest

service:
  type: LoadBalancer 
  protocol: TCP
  mongodb:
    port: 3130

headless:
  app: mongodb
  port: 27017
  ClusterIP: None

---

stateful:
  labels:
    app: mongodb
  serviceName: "mongodb"
  replicas: 3
  name: mongo-data
  mountPath: /data/db
  accessModes: ["ReadWriteOnce"]
  storage: 1Gi
image:
  tag: mongo:latest

storageclasses:
  provisioner: ebs.csi.aws.com
  type: gp3 
  reclaimPolicy: Retain 
  volumeBindingMode: WaitForFirstConsumer

pvc:
  storage: 2Gi
