apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Release.Name }}-headless-svc
  replicas: {{ .Values.stateful.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.stateful.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.stateful.label }}
    spec:
      containers:
      - name: {{ .Values.stateful.containerName }}
        image: "{{ .Values.image.mongodb.repository }}:{{ .Values.image.mongodb.tag }}"
        ports:
        - containerPort: {{ .Values.stateful.containerPort }}
        volumeMounts:
        - name: {{ .Values.stateful.volumeName }}
          mountPath: {{ .Values.stateful.mountPath }}
        env:
        - name: {{ .Values.env.MONGO_INITDB_DATABASE }}
          value: "{{ .Values.config.MONGO_INITDB_DATABASE }}"
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.stateful.volumeName }}
    spec:
      accessModes:
        - {{ .Values.stateful.accessMode }}
      storageClassName: {{ .Values.stateful.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.stateful.storageSize }}