
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
  EMAIL_USER: {{ .Values.secret.EMAIL_USER }}
  EMAIL_PASS: {{ .Values.secret.EMAIL_PASS }}
