apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGODB_URI: "{{ .Values.config.data.MONGODB_URI }}"
  SESSION_SECRET: "{{ .Values.config.data.SESSION_SECRET }}"
  PORT: "{{ .Values.config.data.PORT }}"
  MONGO_INITDB_DATABASE: "{{ .Values.config.data.MONGO_INITDB_DATABASE }}"
