apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: {{ .Values.headless.clusterIP }}
  selector:
    app: {{ .Values.headless.app }}
  ports:
    - port: {{ .Values.headless.port }}
      targetPort: {{ .Values.headless.port }}
