apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: {{ .Values.service.mongodb.clusterIP }}
  selector:
    app: {{ .Values.stateful.label }}
  ports:
    - protocol: {{ .Values.service.mongodb.protocol }}
      port: {{ .Values.service.mongodb.port }}
      targetPort: {{ .Values.stateful.containerPort }}