apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:  # How the volume will be accessed by the pods
    - {{ .Values.stateful.accessModes }}
  resources:
    requests:
      storage:  {{ .Values.pvc.storage }} # the amount of storage requested by the PVC
  storageClassName: {{ .Values.stateful.storageClassName }} # the name of the StorageClass to use for this PVC
