apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: "{{ .Values.image.repository }}:{{ .Value.image.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
          - name: {{ .Values.env.MONGODB_URI }}
            valueFrom:
              configMapKeyRef: 
                name: {{ .Values.config.name }}
                key: {{ .Values.env.MONGODB_URI }}
          - name: {{ .Values.env.SESSION_SECRET }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.config.name }}
                key: {{ .Values.env.SESSION_SECRET }}
          - name: {{ .Values.env.PORT }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.config.name }}
                key: {{ .Values.env.PORT }}
          - name: {{ .Values.env.EMAIL_USER }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.env.EMAIL_USER }}
          - name: {{ .Values.env.EMAIL_PASS }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: {{ .Values.env.EMAIL_PASS }}

