
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.stateful.replicas }}
  serviceName: {{ .Values.stateful.serviceName }}
  selector:
    matchLabels:
      app: {{ .Values.stateful.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.stateful.label}}
    spec:
      containers:
      - name: {{ .Values.stateful.containerName}}
        image: {{ .Values.stateful.image }}
        ports:
        - containerPort: {{ .Values.headless.containerPort }}
        volumeMounts:
          - mountPath: {{ .Values.stateful.mountPath }}
            name: {{ .Values.stateful.volumeName }}
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.name }}
              key: MONGO_INITDB_DATABASE 
  volumeClaimTemplates:  # it is referencing pvc automatically instead of refering pvc manually in the pod or yaml file
    - metadata:
        name: {{ .Values.stateful.volumeName }}
      spec:
        accessModes:
          {{ .Values.stateful.accessModes }}
        storageClassName: {{ .Values.stateful.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.stateful.storageSize }}

