apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}  # Use NodePort if LoadBalancer is not supported
  ports:
    - port: {{ .Values.config.PORT }}
      targetPort: {{ .Values.config.PORT }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.deployment.labels.app }}
