apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-retail-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.retail.type }}
  selector:
    app: {{ .Values.deployment.label }}
  ports:
    - protocol: {{ .Values.service.retail.protocol }}
      port: {{ .Values.service.retail.port }}
      targetPort: {{ .Values.deployment.containerPort }}
