namespace: venkatesh-ns

# secret:
#   name: retail-release-secret 
#   type: Opaque
#   data:
#     EMAIL_USER: Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=
#     EMAIL_PASS: eXhvcSBianVrIHJkbnQgYWx6cA==

# config:
#   name: retail-release-config
#   data:
#     MONGODB_URI: "mongodb://retail-release-headless-svc:27017/myDatabase"
#     SESSION_SECRET: "1234"
#     PORT: "3130"
#     MONGO_INITDB_DATABASE: "myDatabase"

# deployment: 
#   labels:
#     app: retail
#   name: retail-container
#   containerPort: 3130
#   replicas: 4
#   image:
#     repository: saiteja2502/userprofileretail
#     tag: latest

# stateful:
#   replicas: 1
#   containerName: mongodb
#   serviceName: "retail-release-headless-svc"
#   containerPort: 27017
#   label: mongodb
#   volumeName: mongo-volume
#   mountPath: /data/db
#   accessMode: ReadWriteOnce
#   storageSize: 1Gi
#   storageClassName: retail-release-storageclass
#   image: mongo:latest


# service:
#   type: LoadBalancer 
#   protocol: TCP
#   mongodb:
#     port: 3130

# headless:
#   #app: mongodb
#   port: 27017
#   clusterIP: None


# # stateful:
# #   labels:
# #     app: mongodb
# #   serviceName: "retail-release-headless-svc"
# #   replicas: 3
# #   name: mongo-data
# #   mountPath: /data/db
# #   accessModes: ["ReadWriteOnce"]
# #   storage: 1Gi
# #   sc: retail-release-storageclass
# #   image: mongo:latest

# storageclasses:
#   provisioner: ebs.csi.aws.com
#   type: gp3 
#   reclaimPolicy: Retain 
#   volumeBindingMode: WaitForFirstConsumer

# # pvc:
# #   storageClassName: retail-release-storageclass
# #   accessModes: 
# #     ReadWriteOnce
# #   resources:
# #     requests:
# #       storage: 2Gi

# pvc:
#  accessModes: ["ReadWriteOnce"]
#  resources:
#     requests:
#       storage: 2Gi 


deployment:
  replicas: 4
  containerName: retail-container
  containerPort: 3130
  label: retail

stateful:
  replicas: 1
  containerName: mongodb
  containerPort: 27017
  label: mongodb
  volumeName: mongo-volume
  mountPath: /data/db
  accessMode: ReadWriteOnce
  storageSize: 1Gi
  storageClassName: retail-release-storageclass

image:
  repository: saiteja2502/userprofileretail
  tag: latest
  mongodb:
    repository: mongo
    tag: latest

service:
  retail:
    type: LoadBalancer
    port: 3130
    protocol: TCP
  mongodb:
    port: 27017
    protocol: TCP
    clusterIP: None

config:
  MONGODB_URI: mongodb://retail-release-mongodb-svc:27017/myDatabase
  SESSION_SECRET: "1234"
  PORT: "3130"
  MONGO_INITDB_DATABASE: myDatabase

secret:
  type: Opaque
  EMAIL_USER: Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=
  EMAIL_PASS: eXhvcSBianVrIHJkbnQgYWx6cA==

env:
  MONGODB_URI: MONGODB_URI
  SESSION_SECRET: SESSION_SECRET
  PORT: PORT
  EMAIL_USER: EMAIL_USER
  EMAIL_PASS: EMAIL_PASS
  MONGO_INITDB_DATABASE: MONGO_INITDB_DATABASE

pvc:
  storage: 2Gi

storageClass:
  provisioner: ebs.csi.aws.com
  type: gp3
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer